#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define VER_FILE_VERSION_STR "v" STRINGIZE(VERSION_MAJOR) "." STRINGIZE(VERSION_MINOR)
#define VER_PRODUCT_VERSION_STR VER_FILE_VERSION_STR

#endif // VERSION_H
